### PR TITLE
Provide USBGadget Support

### PR DESCRIPTION
**Pull request by MaksymPrymierov**

### CODE REVIEW

**Comment by MaksymPrymierov** [comment]
image

**Comment by MaksymPrymierov** [comment]
Added support for MTP, PTP and ADB USB Gadget modes.
I am going to add support for RNDIS and MIDI modes.

**Comment by MaksymPrymierov** [comment]
I have added RNDIS and MIDI usb gadget modes and performed some VTS and CTS tests/
```
arm64-v8a HalUsbGadgetV1_0HostTest
----------------------------------
com.android.tests.usbgadget.HalUsbGadgetV1_0HostTest (5 Tests)
[1/5] com.android.tests.usbgadget.HalUsbGadgetV1_0HostTest#testMtp: PASSED (3.814s)
[2/5] com.android.tests.usbgadget.HalUsbGadgetV1_0HostTest#testPtp: PASSED (3.768s)
[3/5] com.android.tests.usbgadget.HalUsbGadgetV1_0HostTest#testRndis: PASSED (3.795s)
[4/5] com.android.tests.usbgadget.HalUsbGadgetV1_0HostTest#testMIDI: PASSED (3.818s)
[5/5] com.android.tests.usbgadget.HalUsbGadgetV1_0HostTest#testAndroidUSB: PASSED (70ms)

Summary
-------
arm64-v8a HalUsbGadgetV1_0HostTest: Passed: 5, Failed: 0, Ignored: 0, Assumption Failed: 0 
```
```
arm64-v8a CtsMidiTestCases
--------------------------
android.midi.cts (7 Tests)
[1/7] android.midi.cts.MidiEchoTest#testDeviceCallback: PASSED (1ms)
[2/7] android.midi.cts.MidiEchoTest#testDeviceInfo: PASSED (0ms)
[3/7] android.midi.cts.MidiEchoTest#testEchoBadBehavior: PASSED (0ms)
[4/7] android.midi.cts.MidiEchoTest#testEchoLatency: PASSED (0ms)
[5/7] android.midi.cts.MidiEchoTest#testEchoMultipleMessages: PASSED (0ms)
[6/7] android.midi.cts.MidiEchoTest#testEchoSmallMessage: PASSED (1ms)
[7/7] android.midi.cts.MidiEchoTest#testMidiManager: PASSED (0ms)

Summary
-------
arm64-v8a CtsMidiTestCases: Passed: 7, Failed: 0, Ignored: 0, Assumption Failed: 0
```
```
arm64-v8a CtsUsbManagerTestCases
--------------------------------
android.usb.cts (1 Test)
[1/1] android.usb.cts.UsbManagerApiTest#test_UsbApiSetGetCurrentFunctionsSys: PASSED (3ms)

Summary
-------
arm64-v8a CtsUsbManagerTestCases: Passed: 1, Failed: 0, Ignored: 0, Assumption Failed: 0 
```

**Comment by MaksymPrymierov** [comment]
https://01.org/linuxgraphics/gfx-docs/drm/usb/gadget-testing.html
Documentation about usb gadget modes.
@rsglobal

**Comment by rsglobal** [comment]
@MaksymPrymierov ,

Thank you for this submission. Please rebase into next (don't forget to do `git remote update` to download recent changes)

Could you put more info into the commit message for ("common: Update USB init script for working usb gadget through functionfs"), was it copy-pasted/based on similar AOSP file? Could you put a permalink to that file?

**Pull request merged**
