### PR TITLE
Pinephone: initial RIL + GPS support

### PR DESCRIPTION
**Pull request by bauner**
https://github.com/GloDroid/glodroid_device/commit/91e328f5e84b7abd66526a9198d20c93718c8434

### CODE REVIEW

**Comment by genofire** [comment]
anything stopping this PR to merge?

**Comment by rsglobal** [comment]
Hi,

There is 2 major reasons:
1. I haven't managed to get it work on Android-11
2. We are trying to minimize number of proprietary components in our builds

We will have to create RIL and GNSS HAL components by our-self using Google templates and Linux pinephone experience.
But currently there is no free developers available to do this work within GloDroid team.

**Comment by toitoine38** [comment]
Hi,
All my apologies for this comment which does not concern this topic but I have a question for bauner and I dont know how to send it to/contact him directly. This is not a spam, I have a question on LineageOS 15.1 for n7000 (update and security patch) for him and I saw that bauner participates to this pull request.
Bauner, how can I contact you to ask you my question ? I can give you my mail if it's ok for you.

Thanks in advance for your response and sorry again for the disturbance.
Antoine

**Comment by rsglobal** [comment]
FOSS RIL support was introduced in [v0.7.0](https://github.com/GloDroid/glodroid_manifest/releases/tag/v0.7.0)

We plan to improve it to make usable instead of using proprietary RIL.

**Pull request closed without merging**
