### PR TITLE
Build mesa3d with meson

### PR DESCRIPTION
**Pull request by rsglobal**
Depends on https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/10183

### CODE REVIEW

**Comment by MarijnS95** [comment]
~~Is Freedreno specifically enabling compilation of `libmesa_util`? One of the `libcutils` headers requires headers from `bionic/libc/include`:~~

```c
 -o src/util/libmesa_util.a.p/os_misc.c.o -c ../../../../../../external/mesa3d/src/util/os_misc.c
In file included from ../../../../../../external/mesa3d/src/util/os_misc.c:59:
system/core/libcutils/include/cutils/properties.h:22:10: fatal error: 'sys/system_properties.h' file not found
#include <sys/system_properties.h>
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

~~Have you ran into this yet? Adding bionic headers breaks host includes completely, which I don't think should be used in the first place:~~

```c
-o src/util/libmesa_util.a.p/u_debug_stack_android.cpp.o -c ../../../../../../external/mesa3d/src/util/u_debug_stack_android.cpp
In file included from ../../../../../../external/mesa3d/src/util/u_debug_stack_android.cpp:24:
In file included from system/core/libbacktrace/include/backtrace/Backtrace.h:23:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/string:38:
In file included from /usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/x86_64-pc-linux-gnu/bits/c++config.h:518:
/usr/lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/x86_64-pc-linux-gnu/bits/os_defines.h:44:5: error: function-like macro '__GLIBC_PREREQ' is not defined
#if __GLIBC_PREREQ(2,15) && defined(_GNU_SOURCE)
    ^
...
```

EDIT: That's my problem, I redirected the compiler from the NDK to use AOSP prebuilt clang instead, but the NDK does quite some wrapping to use an alternative sysroot that _also_ (unexpectedly) provides the missing header.

**Comment by rsglobal** [comment]
Current status:
1. "Android" label works. SystemUI fails presumably due to missing 32bit libs.
2. Format Modifier support aren't enabled (buffers are displayed not correctly).

**Comment by rsglobal** [comment]
>  Format Modifier support aren't enabled (buffers are displayed not correctly).

FIXED (GloDroid/glodroid_forks#9 updated)

**Comment by rsglobal** [comment]
Makefiles migrated to https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/10183

**Pull request merged**
